org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
neo_version=21.1.228

mod_id=crafterssoccer
mod_name=CraftersSoccer
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=org.crafterscr.crafterssoccer
mod_authors=Crafters CR
mod_description=Sistema de fútbol con balón físico y tiros cargados.

player_anim_version=2.0.1+1.21.1

bendy_lib_version=5.1
